name: common_ui
description: "flutter common ui package"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
#  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #ui - widget
  nav: ^1.3.9
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  webview_flutter_wkwebview: ^3.18.1

  #ui - resource
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2

  #data
  uuid: ^4.5.1
  shared_preferences: ^2.5.2
  isar: ^3.1.0+1  #local db
  isar_flutter_libs: ^3.1.0+1

  #network
  dio: ^5.8.0+1
  retrofit: ^4.4.2

  #util
  velocity_x: ^4.3.1
  logger: ^2.5.0
  image_picker: ^1.1.2
  alice: ^1.0.0-dev.12 # network log screen
  alice_dio: ^1.0.4
  url_launcher: ^6.3.1

  #ui - util
  #  flutter_keyboard_visibility: ^6.0.0
  keyboard_utils_fork:
    git:
      url: https://github.com/BansookNam/keyboard_utils.git
      ref: 'master'


  #firebase
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  path_provider: ^2.1.5
#  firebase_messaging: ^15.2.4

dependency_overrides:
#  # velocity_x 와 velocity_x 에서 사용하는 intl 버전이 달라 충돌이 발생하기에 intl를 0.20.2 버전으로 override 고정
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
    - assets/images/
    - assets/images/flag/